name: File copy test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Copy file...
        run: |
          touch test
          cp test test_1
      - name: Run my script...
        run:  bash ${GITHUB_WORKSPACE}/.scripts/test_script.sh
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"
      - name: Final check...
        run: |
          echo All is good!!

