name: File copy test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Copy file...
        run: |
          touch test
          cp test test_1
      - name: Run my script...
        run:  bash ${GITHUB_WORKSPACE}/.scripts/test_script.sh
      - name: Get Head Commit Message
        id: get_head_commit_message
        run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
      - name: Print the commit message
        id: print_msg
        run: |
          printf '%s\n' "$HEAD_COMMIT_MESSAGE" # This will output 'commit message'
      - name: Final check...
        run: |
          echo All is good!!

