name: File copy test
on: [push]
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Copy file...
      run: |
        touch test
        cp test test_1
    - name: Final check...
      run: |
        echo All is good!!
