name: File copy test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Copy file...
        run: |
          touch test
          cp test test_1
      - name: Run my script...
        run:  bash ${GITHUB_WORKSPACE}/.scripts/test_script.sh
      - name: Final check...
        run: |
          echo All is good!!

