name: File copy test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Copy file...
        run: |
          touch test
          cp test test_1
      - name: Run my script...
        run:  bash ${GITHUB_WORKSPACE}/.scripts/test_script.sh
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Print Head Commit Message and ref
        id: get_head_commit_message
        run: |
          echo "Commit message=${{ github.event.head_commit.message }}"
          echo "Ref=${{ github.event.ref}}"
      - name: Check if commit has contains JIRA id
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"JIRA-"* ]]; then
            echo "Commit has a JIRA id, check ok"
          else
            echo "Variable does not contain JIRA id"
            exit 1
          fi
      - name: Final check...
        run: |
          echo All is good!!

