name: PR verify pipeline
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Print Head Commit Message and ref
        run: |
          echo "Commit message=${{ github.event.head_commit.message }}"
          echo "Ref=${{ github.event.ref}}"
      - name: Print commit messages
        run: |
          PR_NUMBER="${{ github.event.number }}"
          COMMITS=$(curl -sSL "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.[].commit.message')

          echo "Commit messages for Pull Request #${PR_NUMBER}:"
          echo "$COMMITS"
      - name: Final check...
        run: |
          echo All is ok!!
